In [5]:
from pathlib import Path
import numpy as np
from utils import readnp

In [22]:
def read():
    lines = Path(f'data/08.txt').read_text().rstrip().split('\n')
    return np.array([[int(i) for i in line] for line in lines])

In [128]:
test = '''
30373
25512
65332
33549
35390
'''
test = test.strip().split('\n')
test = np.array([[int(i) for i in line] for line in test])

In [91]:
def visible(X):
    X = np.atleast_2d(X)
    ma = np.maximum.accumulate(X,axis=1)
    neg1 = np.full(fill_value=-1,shape=(ma.shape[0], 1))
    return X > np.hstack([neg1, ma[:,:-1]])

In [92]:
A = read()

In [121]:
A

array([[0, 1, 2, ..., 3, 0, 1],
       [2, 0, 0, ..., 2, 3, 2],
       [0, 1, 2, ..., 2, 0, 2],
       ...,
       [3, 2, 1, ..., 1, 0, 1],
       [3, 2, 1, ..., 3, 3, 1],
       [2, 3, 1, ..., 0, 3, 0]])

In [134]:
def all_visible(A):
    V = np.full_like(A, fill_value=False, dtype=bool)
    for k in range(4):
        V = V | np.rot90(visible(np.rot90(A,k)), -k)
    return V

In [135]:
all_visible(test)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [136]:
test

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [137]:
all_visible(test).sum()

21

In [139]:
all_visible(A).sum()

1693

In [247]:
def count(X):
    if len(X) == 1:
        return 0
    x = X[0]
    for idx, y in enumerate(X[1:]):
        if y >= x:
            break
    return idx + 1

In [248]:
test

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [256]:
def count_four(A, i,j, verbose=False):
    r = count(A[i,j:])
    d = count(A[i:,j])
    u = count(A[:i+1,j][::-1]) 
    l = count(A[i,:j+1][::-1])
    if verbose:
        print(i,j, ':', u,l,d,r)
    return u*l*d*r                 

In [257]:
count_four(test, 3,2, verbose=True)

3 2 : 2 2 1 2


8

In [265]:
def count_all(A):
    O = np.zeros_like(A)
    for i, j in np.ndindex(A.shape):
        O[i,j] = count_four(A, i,j)
    return O

In [266]:
count_all(test).max()

8

In [267]:
count_all(A).max()

422059